# Site settings
title: OpenHack Syracuse
header-img: img/home-bg.jpg
description: "OpenHack Syracuse is a local meetup for developers, designer, and creators of all shapes, sizes and abilities"
baseurl: ""
url: "http://openhacksyr.com"
twitter_username: OpenHackSYR
github_username:  OpenHackSYR
newsletter_url: "http://tinyletter.com/openhacksyr"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: "/blog/:year/:month/:title/"
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

jekyll-mentions: https://twitter.com

# gems:
#   - jekyll-sitemap
#   - jekyll-mentions
